-- Scrapbook (notes) lists alongside shopping and task lists.
--
-- Adds a third `kind` value, `'notes'`: a freeform collection of saved scraps
-- (typed notes, voice memos, links). Like task lists, notes reuse the items
-- table — `name` is the title, plus two new optional columns:
--   - `note`: an optional longer body (typed or spoken transcript)
--   - `url` : an optional link (auto-unfurled into a rich card client-side)
-- Both columns are nullable and ignored by shopping/task rows, so existing rows
-- and code paths are unaffected.

-- 1. Extend the list-kind CHECK ---------------------------------------------
-- Postgres has no "add value to CHECK" — drop and re-add. The constraint name
-- was auto-generated by migration 0025 (`lists_kind_check`); drop it if-exists
-- to stay idempotent across environments.
alter table public.lists
  drop constraint if exists lists_kind_check;
alter table public.lists
  add constraint lists_kind_check check (kind in ('shopping', 'task', 'notes'));

-- 2. Notes item fields -------------------------------------------------------
alter table public.items
  add column if not exists url text null,
  add column if not exists note text null;

-- 3. Keep notes out of the grocery autocomplete history ----------------------
-- bump_item_history (migration 0026) already skips task lists; extend the guard
-- to also skip notes — link titles and memos aren't groceries. Everything else
-- is unchanged from 0026.
create or replace function public.bump_item_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Task and notes items aren't groceries — don't pollute the autocomplete history.
  if (select kind from public.lists where id = new.list_id) in ('task', 'notes') then
    return new;
  end if;

  insert into public.user_item_history (user_id, name, last_used_at, use_count, category)
  values (new.added_by, new.name, now(), 1, new.category)
  on conflict (user_id, lower(name)) do update
    set last_used_at = excluded.last_used_at,
        use_count    = public.user_item_history.use_count + 1,
        category     = coalesce(excluded.category, user_item_history.category);
  return new;
end;
$$;
